package com.example.domain.models


import kotlinx.collections.immutable.PersistentList
import kotlinx.serialization.Serializable


@Serializable
data class ConfigModel3(
    val cmd: String? = "",
    val code: Int? = 0,
    val `data`: Data? = null,
    val http_response: Int? = null,
    val message: String? = null,
    val success: Boolean? = null
) {
    @Serializable
    data class Data(
        val configs: Configs?,
        val instructions_list: PersistentList<String>?,
        val interested_categories: PersistentList<String?>?,
        val location: Location?,
        val password_rules: PersistentList<PasswordRule?>?,
        val tutorials_list: PersistentList<String>?,
        val visa_category_list: PersistentList<VisaCategory?>?
    ) {
        @Serializable
        data class Configs(
            val OUTLET_COUNT_PLURAL: String?,
            val OUTLET_COUNT_SINGULAR: String?,
            val SAVED_THIS_YEAR_LABEL: String?,
            val TRAVEL_LOCATION: String?,
            val Two_People_: String?,
            val access_restricted_to_application: String?,
            val activation_of_trial: String?,
            val branch_deactivated_key: String?,
            val branch_invalid_key: String?,
            val branch_used_key: String?,
            val branch_valid_key: String?,
            val buy_more: String?,
            val charity_donation_deeplink: String?,
            val charity_donation_denominations: String?,
            val contact_email: String?,
            val countries_version: String?,
            val currency: String?,
            val customer_does_not_own_offer_x: String?,
            val customer_has_already_redeemed_offer_x_the_maximum_allowed_times: String?,
            val customer_register_success: String?,
            val customer_with_this_email_address_already_exists: String?,
            val customer_with_this_email_address_exists: String?,
            val demographics_form_cancelable: String?,
            val demographics_is_active: String?,
            val display_yas_benefits_list: Boolean?,
            val email_and_key_required: String?,
            val email_not_exist: String?,
            val email_password_required: String?,
            val email_required: String?,
            val email_service_enabled: Boolean?,
            val emid_placeholder_text: String?,
            val emp_code_is_required: String?,
            val enable_signature_encryption: Boolean?,
            val enquiry_success_message: String?,
            val error_code_message_ar: String?,
            val error_code_message_en: String?,
            val faqs: String?,
            val favourite_outlets_params: String?,
            val filters_version: String?,
            val for_given_key_values_are_not_found: String?,
            val gdpr_consent_message: String?,
            val gdpr_consent_no: String?,
            val gdpr_consent_title: String?,
            val gdpr_consent_yes: String?,
            val gems_featured_heading: String?,
            val gems_more_to_enjoy: String?,
            val gems_points_reflect_message: String?,
            val gems_user_id_and_password_is_required: String?,
            val getaways_pre_popup_title: String?,
            val getaways_section_button_title: String?,
            val getaways_section_title: String?,
            val help_and_live_chat: String?,
            val hotel_rule_of_use: String?,
            val hsbc_more_to_enjoy: String?,
            val hsbc_more_to_enjoy_group2: String?,
            val informatica_error: String?,
            val instruction_screen_text_1: String?,
            val instruction_screen_text_2: String?,
            val instruction_screen_text_3: String?,
            val instruction_screen_text_4: String?,
            val instruction_screen_text_5: String?,
            val instruction_screen_url_1: String?,
            val instruction_screen_url_2: String?,
            val instruction_screen_url_3: String?,
            val instruction_screen_url_4: String?,
            val instruction_screen_url_5: String?,
            val interested_category_1_ar: String?,
            val interested_category_2_ar: String?,
            val interested_category_3_ar: String?,
            val interested_category_4_ar: String?,
            val interested_category_5_ar: String?,
            val interested_category_6_ar: String?,
            val interested_category_7_ar: String?,
            val interested_category_8_ar: String?,
            val invalid_email_address: String?,
            val invalid_login_or_password: String?,
            val invalid_merchant_pin: String?,
            val invalid_password: String?,
            val invalid_vip_key: String?,
            val invoice_validation_outdated_invoice: String?,
            val invoice_validation_success_message_upgraded: String?,
            val is_bell_icon_enabled: Boolean?,
            val is_captcha_verification: Boolean?,
            val is_s_p: String?,
            val is_visa_category_popup_enabled: Boolean?,
            val license_agreement: String?,
            val linked_entertainer_account_to_facebook: String?,
            val location_category_hotels: String?,
            val merchant_does_not_exist: String?,
            val more_from_vodafone: String?,
            val no_offers_specified: String?,
            val not_authorized_to_access_key: String?,
            val not_authorized_to_access_user: String?,
            val not_implemented: String?,
            val offer_can_be_redeemed_a_maximum_of_x_times_you_requested_y_times: String?,
            val offer_does_not_exist: String?,
            val offer_does_not_exist_or_inactive: String?,
            val offer_tag_express: String?,
            val offer_tag_live: String?,
            val offer_tag_promo_code: String?,
            val offer_tag_resuable: String?,
            val offer_x_is_not_available_at_outlet_y: String?,
            val offers_must_belong_to_the_same_merchant: String?,
            val otp_is_incorrect: String?,
            val otp_message_android: String?,
            val otp_resend_successfully: String?,
            val otp_send_successfully: String?,
            val parent_id_is_required: String?,
            val parent_id_is_required_dhl: String?,
            val parent_id_is_required_dpr: String?,
            val parent_id_is_required_uex: String?,
            val password_reset_link_sent_message: String?,
            val phone_number_is_required: String?,
            val point_gifting_notification_desc: String?,
            val point_gifting_notification_title: String?,
            val points_gifting_denominations: String?,
            val privacy_policy: String?,
            val problems_with_customer_devices_record_deleting: String?,
            val problems_with_saving_of_family_member_info: String?,
            val problems_with_your_submission: String?,
            val promo_code_coupon_apply_discount_btn_text: String?,
            val promo_code_coupon_dismiss_btn_text: String?,
            val promo_code_coupon_dismiss_btn_text_color: String?,
            val promo_code_coupon_step1_text: String?,
            val promo_code_coupon_step1_title: String?,
            val promo_code_coupon_step2_text: String?,
            val promo_code_coupon_step2_title: String?,
            val promo_code_discount_code_tooltip: String?,
            val promo_code_swipe_redemption_des: String?,
            val promo_code_tooltip_subtitle: String?,
            val promo_code_tooltip_title: String?,
            val qgi_more_to_enjoy: String?,
            val quiqup_service_delay_message: String?,
            val resend_otp_only_works_after_30_seconds: String?,
            val rule_of_use: String?,
            val savings_message_welcome_guest: String?,
            val show_and_go_tab_id: String?,
            val social_id_not_tied_to_magento_customer_account: String?,
            val success_vip_key_applied_and_product_unlocked: String?,
            val support_phone: Boolean?,
            val tab_name_BNE: String?,
            val tab_name_HSBC: String?,
            val tab_name_all_offers: String?,
            val tab_name_all_offers_crg: String?,
            val tab_name_all_offers_gems: String?,
            val tab_name_all_offers_jge: String?,
            val tab_name_all_offers_kelloggs: String?,
            val tab_name_all_offers_landmark_group: String?,
            val tab_name_buy_more: String?,
            val tab_name_cheers: String?,
            val tab_name_delivery: String?,
            val tab_name_hsbc_fine_dining: String?,
            val tab_name_hsbc_i_love_dining: String?,
            val tab_name_monthly: String?,
            val tab_name_more_sa: String?,
            val tab_name_new: String?,
            val terms_and_conditions: String?,
            val terms_and_conditions_ar: String?,
            val there_are_no_customer_devices_belonging_to_the_specified_customer: String?,
            val there_is_no_such_record: String?,
            val travel_section_button_title: String?,
            val travel_section_title: String?,
            val tutorials_max_allowed_sessions: String?,
            val upgrade_app: String?,
            val upgrade_app_lmk: String?,
            val user_already_exisit_gems_message: String?,
            val user_already_registered_gems_message: String?,
            val user_already_registered_yah_message: String?,
            val vdf_more_to_enjoy: String?,
            val verify_email_continue_button_title: String?,
            val verify_email_continue_message: String?,
            val verify_email_resend_btn_title: String?,
            val verify_email_sent_message: String?,
            val vip_key_already_used: String?,
            val welcome: String?,
            val wrong_device_install_token: String?,
            val wrong_session_token: String?,
            val yas_benefits_group_for_employees: String?,
            val yas_benefits_group_for_residents: String?,
            val you_are_not_allowed_to_access_this_application: String?,
            val you_are_not_authorized_to_access_this_key: String?,
            val you_are_not_authorized_to_access_this_user: String?,
            val you_are_not_authorized_to_delete_this_customer_devices_record: String?,
            val you_have_successfully_activated_the_key_with_branch: String?
        )

        @Serializable
        data class Location(
            val currency: String?,
            val id: String?,
            val name: String?
        )

        @Serializable
        data class PasswordRule(
            val info_text: String?,
            val invalid_icon: String?,
            val invalid_text_color: String?,
            val rule: String?,
            val type: String?,
            val valid_icon: String?,
            val valid_text_color: String?
        )

        @Serializable
        data class VisaCategory(
            val visa_type: String?,
            val visa_type_id: String?
        )
    }
}